name: goapp-service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: vishal267
      IMAGE_TAG: thefinisher-goapp-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}:latest
          ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}:${{ github.sha }}  # Add commit SHA as tag
        cache-from: type=registry, ref=${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}:cache
        cache-to: type=registry, ref=${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}:cache, mode=max  # Use caching


    - name: Cleanup
      run: docker system prune -f
