name: goapp-service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: vishal267
      IMAGE_TAG: thefinisher-goapp-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/thefinisher-goapp-service:${{ env.IMAGE_TAG }}
          ${{ env.DOCKER_USERNAME }}/thefinisher-goapp-service:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/thefinisher-goapp-service:cache
        cache-to: type=registry,ref=${{ env.DOCKER_USERNAME }}/thefinisher-goapp-service:cache,mode=max

    - name: Cleanup
      run: docker system prune -f
